title: International Workshop on Internet of Things Pervasive Real-World Deployments (IoT-PROD)
description: In conjunction with 2022 IEEE International Conference on Pervasive Computing and Communications (PerCom 2022), March 21-25, 2022, in Pisa, Italy. 
theme: jekyll-theme-cayman
github:
  is_project_page: false
